//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.21 at 02:25:18 pm IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://interfaces.app.employeesoapcrud.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.employeesoapcrud.app.interfaces;
